# Generated by Django 4.0.6 on 2022-07-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spech', models.CharField(max_length=2000)),
                ('price', models.FloatField()),
                ('offer_price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.CharField(max_length=2000)),
            ],
        ),
    ]
